
using System.IO;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace pocPagSeguro.Controllers
{
    public class TesteController : Controller
    {

        public FileResult Index()
        {
            var mr = new MemoryStream();
            var tw = new StreamWriter(mr);
            // tw.WriteLine("MIIQ5AYJKoZIhvcNAQcCoIIQ1TCCENECAQExCzAJBgUrDgMCGgUAMHoGCSqGSIb3DQEHAaBtBGt7");
            // tw.WriteLine("InRlYW1JZCI6IjNNTjJNMjhKMkEiLCJkb21haW4iOiJwYWdhbWVudG8ua2VzaWFrbGF2YS5jb20i");
            // tw.WriteLine("LCJkYXRlQ3JlYXRlZCI6IjIwMTktMDEtMzAsMjI6MzU6NDAiLCJ2ZXJzaW9uIjoxfaCCDbEwggPz");
            // tw.WriteLine("MIIC26ADAgECAgEXMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBs");
            // tw.WriteLine("ZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMN");
            // tw.WriteLine("QXBwbGUgUm9vdCBDQTAeFw0wNzA0MTIxNzQzMjhaFw0yMjA0MTIxNzQzMjhaMHkxCzAJBgNVBAYT");
            // tw.WriteLine("AlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1");
            // tw.WriteLine("dGhvcml0eTEtMCsGA1UEAxMkQXBwbGUgaVBob25lIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIB");
            // tw.WriteLine("IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAox6-8EfAtJ4QW0akuCG4T4YhcChFYFwcw8gK");
            // tw.WriteLine("ZGOI-_xp7vhU_OlbtwZOBC_DazOvREzqS4AJtIf2W7T9ZN2zcuATs_0X2bznqO3CjGHCKvnszqVe");
            // tw.WriteLine("1mnrZAuNCI-4oFBGCdwZ5OWwlG2795mYxOibQU7U8WXjG1J63OgD2W4d2hBVhqQpWEkM6kfXFTQz");
            // tw.WriteLine("9sCgREpwviy1KjA3jC4V69HkbJc4VVaxNStY6kSjJoXuyGZK5M-J8D1jrSnerbpas9ylo5qnCU6A");
            // tw.WriteLine("FjVlpIUNY3s-Y4rafUpG7KM5GDS5xihlGLwTYJx_V6wUyYntobaHaFK2hE64yIPs-Z4Zq7PBC4bH");
            // tw.WriteLine("nwIDAQABo4GcMIGZMA4GA1UdDwEB_wQEAwIBhjAPBgNVHRMBAf8EBTADAQH_MB0GA1UdDgQWBBTn");
            // tw.WriteLine("NCouIt45YGu0lM53g2EvMaB8NTAfBgNVHSMEGDAWgBQr0GlHlHYJ_vRrjS5ApvdHTX8IXjA2BgNV");
            // tw.WriteLine("HR8ELzAtMCugKaAnhiVodHRwOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhL3Jvb3QuY3JsMA0GCSqG");
            // tw.WriteLine("SIb3DQEBBQUAA4IBAQAd0dV73XRO1xf8gi0MmZteQnLyadzVa14NDGtLPnsUJd6zlOig-g-AifIX");
            // tw.WriteLine("PQACopGRvnRX3K-an6EKfTC-ACrMIVnr_UmsbnUZ6Jp6A9GG9uf2sA5LSfqjt0G619HjVqF9g6uX");
            // tw.WriteLine("rvhRSibBhUITJo0DVGYQXmCEBRIxK2tUwKDIQbxUHudUrRMA0krHu8GKr4EIjvBGCr8npr7czzk6");
            // tw.WriteLine("gHAZIzKja2Zdnk2oR0mye0W1UTOndGcJTrZsb0j3LLkzBURrRb50S2-yhpG0PiUoJZ6zwlGG_E_l");
            // tw.WriteLine("rzuqu0QsAUnidLM0-kTvFMIR8i0ZGlGJ0whKQWxYVt6bOuEFV-Viz9IPMIID-DCCAuCgAwIBAgII");
            // tw.WriteLine("PXIg48-M8iUwDQYJKoZIhvcNAQEFBQAweTELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIElu");
            // tw.WriteLine("Yy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MS0wKwYDVQQDEyRBcHBs");
            // tw.WriteLine("ZSBpUGhvbmUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwNzExMDEzNTI1WhcNMjIwNDEy");
            // tw.WriteLine("MTc0MzI4WjBZMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjE1MDMGA1UEAwwsQXBw");
            // tw.WriteLine("bGUgaVBob25lIE9TIFByb3Zpc2lvbmluZyBQcm9maWxlIFNpZ25pbmcwggEiMA0GCSqGSIb3DQEB");
            // tw.WriteLine("AQUAA4IBDwAwggEKAoIBAQDn2ZrDF6PJ6QfVx5mktHUhTBEDaB8wLAecd4gxSMhEBI2BzXrG-NP2");
            // tw.WriteLine("RxxtTu665hSFccTvebNLddpohaZzVaLGh1F71xyBtQFq44yR7noq_M-VXvlxoCh--avU4c4OT5Xz");
            // tw.WriteLine("yu23lQoy_yWZNvaYnSSLZFe29f2-RSH5rkR2t-qwO2mfbX9-1xGbsupDouX9JkfOzMQH4ud1xtv8");
            // tw.WriteLine("fha1pJPGfK89vd3AL4B4djpOfNhkTyolUYdBdg5u4JOkIao-Xcpfp4sLQKUvs7NqSsfGU7UfXCyK");
            // tw.WriteLine("iO7kkC-f3VI-FkHGOB5oJI8xLdtpcc-g80IaKBFKdJym1nhJWA3EvBxb8T17AgMBAAGjgaMwgaAw");
            // tw.WriteLine("HQYDVR0OBBYEFKReazv8ekdykXAJwSS9LzvJe6C-MAwGA1UdEwEB_wQCMAAwHwYDVR0jBBgwFoAU");
            // tw.WriteLine("5zQqLiLeOWBrtJTOd4NhLzGgfDUwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL2NybC5hcHBsZS5j");
            // tw.WriteLine("b20vaXBob25lLmNybDALBgNVHQ8EBAMCB4AwEQYLKoZIhvdjZAYCAgEEAgUAMA0GCSqGSIb3DQEB");
            // tw.WriteLine("BQUAA4IBAQCKtlZOQdKx8yFDnQvZx_-0mFiZ7UGnMPHv29qAbSG2s1zcvofxOSG8xKHaJtLtpvHt");
            // tw.WriteLine("wBGVGaxHuCoOaZjU5ubOa-oiwSunAW5BTCwd4yOMhiejjBeczBvu2GQzD0QOiztIYhNiVNNxTZIt");
            // tw.WriteLine("gTr_psuOXENxbIgzIjwgPx14uf8aKiHoc2nPm6Gh4T3pDBe8qXPX6VK6wrYfoSKFPrhcGrKae5_M");
            // tw.WriteLine("y1A6_pbH_EhH9CSirT5M-0rbZ5wDcRUnP4NS-7L0GRapPqnsFOxewgqn803RMKrUrbgyoVAvTVXI");
            // tw.WriteLine("QiesHM5yZPAs4AnkTLkLIDU3nNULkcQxHdAr4lyCvX3Q_giZMIIFujCCBKKgAwIBAgIBATANBgkq");
            // tw.WriteLine("hkiG9w0BAQUFADCBhjELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFEFwcGxlIENvbXB1dGVyLCBJbmMu");
            // tw.WriteLine("MS0wKwYDVQQLEyRBcHBsZSBDb21wdXRlciBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxKTAnBgNVBAMT");
            // tw.WriteLine("IEFwcGxlIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTA1MDIxMDAwMTgxNFoXDTI1MDIx");
            // tw.WriteLine("MDAwMTgxNFowgYYxCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRBcHBsZSBDb21wdXRlciwgSW5jLjEt");
            // tw.WriteLine("MCsGA1UECxMkQXBwbGUgQ29tcHV0ZXIgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MSkwJwYDVQQDEyBB");
            // tw.WriteLine("cHBsZSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC");
            // tw.WriteLine("AQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnR");
            // tw.WriteLine("ymacJGsR0KO75Bsqwx-VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV_X5vyJQO6VY9NXQ3xZDUj");
            // tw.WriteLine("FUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw-dPfMrSSgayP7OtbkO2V4c1ss9");
            // tw.WriteLine("tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4--NwzeajTEV-H0xrUJZBicR0YgsQg0GH");
            // tw.WriteLine("M4qBsTBY7FoEMoxos48d3mVz_2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAi8wggIrMA4GA1UdDwEB");
            // tw.WriteLine("_wQEAwIBBjAPBgNVHRMBAf8EBTADAQH_MB0GA1UdDgQWBBQr0GlHlHYJ_vRrjS5ApvdHTX8IXjAf");
            // tw.WriteLine("BgNVHSMEGDAWgBQr0GlHlHYJ_vRrjS5ApvdHTX8IXjCCASkGA1UdIASCASAwggEcMIIBGAYJKoZI");
            // tw.WriteLine("hvdjZAUBMIIBCTBBBggrBgEFBQcCARY1aHR0cHM6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRl");
            // tw.WriteLine("YXV0aG9yaXR5L3Rlcm1zLmh0bWwwgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBj");
            // tw.WriteLine("ZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFw");
            // tw.WriteLine("cGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0");
            // tw.WriteLine("ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wRAYDVR0fBD0w");
            // tw.WriteLine("OzA5oDegNYYzaHR0cHM6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5L3Jvb3Qu");
            // tw.WriteLine("Y3JsMFUGCCsGAQUFBwEBBEkwRzBFBggrBgEFBQcwAoY5aHR0cHM6Ly93d3cuYXBwbGUuY29tL2Nl");
            // tw.WriteLine("cnRpZmljYXRlYXV0aG9yaXR5L2Nhc2lnbmVycy5odG1sMA0GCSqGSIb3DQEBBQUAA4IBAQCd2i0o");
            // tw.WriteLine("WC99dgS5BNM-zrdmY06PL9T-S61yvaM5xlJNBZhS9YlRASR5vhoy9-VEi0tEBzmC1lrKtCBe2a4V");
            // tw.WriteLine("XR2MHTK_ODFiSF3H4ZCx-CRA-F9Ym1FdV53B5f88zHIhbsTp6aF31ywXJsM_65roCwO66bNKcusz");
            // tw.WriteLine("CVut5mIxauivL9WvHld2j383LS4CXN1jyfJxuCZA3xWNdUQ_eb3mHZnhQyw-rW--uaT-DjUZUWOx");
            // tw.WriteLine("w961kj5ReAFziqQjyqSI8R5cH0EWLX6VCqrpiUGYGxrdyyC_R14MJsVVNU3GMIuZZxTHCR-6R8fa");
            // tw.WriteLine("AQmHJEKVvRNgGQrv6n8Obs3BREM6StXjMYICjDCCAogCAQEwgYUweTELMAkGA1UEBhMCVVMxEzAR");
            // tw.WriteLine("BgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5");
            // tw.WriteLine("MS0wKwYDVQQDEyRBcHBsZSBpUGhvbmUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkCCD1yIOPPjPIl");
            // tw.WriteLine("MAkGBSsOAwIaBQCggdwwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcN");
            // tw.WriteLine("MTkwMTMwMjIzNTQwWjAjBgkqhkiG9w0BCQQxFgQUnry2TKq3lgTp1xT2Tx60wBfkTZMwKQYJKoZI");
            // tw.WriteLine("hvcNAQk0MRwwGjAJBgUrDgMCGgUAoQ0GCSqGSIb3DQEBAQUAMFIGCSqGSIb3DQEJDzFFMEMwCgYI");
            // tw.WriteLine("KoZIhvcNAwcwDgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3");
            // tw.WriteLine("DQMCAgEoMA0GCSqGSIb3DQEBAQUABIIBAG5KmIHuGnIoUMlgKPIZqoA_fVgIsirVb_oICMIDjeCT");
            // tw.WriteLine("P22dlV7c02U3G1Hz8hfNucbwIF20jjgwohBbQ2BVbnVlvc2dVo_CBUquRbwl1PZ5_d6nNm-Rezyd");
            // tw.WriteLine("l6zoc2RU_A8ptgaUvjDObdMT1XlJt-oMor8is4szRZCjEnh666x4TWncsP3nCYIgw5QdmpYc7wd-");
            // tw.WriteLine("mLJyH1c5n3lDf_J9GRH22RSoKQO7Zq6WpTzqvgkkDBEQbMtBdLGltzrsAS1YMELpYFxMDyu-Tnvf");
            // tw.WriteLine("z5cV-M4s_X-MTxZQqJcpx6xZc5sgAK-He4yCagB71mai0alhCfp5F-GnY0jzbAdZSAnQyrA");
            //tw.Flush();
tw.WriteLine("MIIQ6QYJKoZIhvcNAQcCoIIQ2jCCENYCAQExCzAJBgUrDgMCGgUAMH8GCSqGSIb3DQEHAaByBHB7");
tw.WriteLine("InRlYW1JZCI6IjNNTjJNMjhKMkEiLCJkb21haW4iOiJwb2NwYXltZW50cy5henVyZXdlYnNpdGVz");
tw.WriteLine("Lm5ldCIsImRhdGVDcmVhdGVkIjoiMjAxOS0wMS0zMCwyMzoxODo0NSIsInZlcnNpb24iOjF9oIIN");
tw.WriteLine("sTCCA_MwggLboAMCAQICARcwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoT");
tw.WriteLine("CkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYD");
tw.WriteLine("VQQDEw1BcHBsZSBSb290IENBMB4XDTA3MDQxMjE3NDMyOFoXDTIyMDQxMjE3NDMyOFoweTELMAkG");
tw.WriteLine("A1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRp");
tw.WriteLine("b24gQXV0aG9yaXR5MS0wKwYDVQQDEyRBcHBsZSBpUGhvbmUgQ2VydGlmaWNhdGlvbiBBdXRob3Jp");
tw.WriteLine("dHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCjHr7wR8C0nhBbRqS4IbhPhiFwKEVg");
tw.WriteLine("XBzDyApkY4j7_Gnu-FT86Vu3Bk4EL8NrM69ETOpLgAm0h_ZbtP1k3bNy4BOz_RfZvOeo7cKMYcIq");
tw.WriteLine("-ezOpV7WaetkC40Ij7igUEYJ3Bnk5bCUbbv3mZjE6JtBTtTxZeMbUnrc6APZbh3aEFWGpClYSQzq");
tw.WriteLine("R9cVNDP2wKBESnC-LLUqMDeMLhXr0eRslzhVVrE1K1jqRKMmhe7IZkrkz4nwPWOtKd6tulqz3KWj");
tw.WriteLine("mqcJToAWNWWkhQ1jez5jitp9SkbsozkYNLnGKGUYvBNgnH9XrBTJie2htodoUraETrjIg-z5nhmr");
tw.WriteLine("s8ELhsefAgMBAAGjgZwwgZkwDgYDVR0PAQH_BAQDAgGGMA8GA1UdEwEB_wQFMAMBAf8wHQYDVR0O");
tw.WriteLine("BBYEFOc0Ki4i3jlga7SUzneDYS8xoHw1MB8GA1UdIwQYMBaAFCvQaUeUdgn-9GuNLkCm90dNfwhe");
tw.WriteLine("MDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly93d3cuYXBwbGUuY29tL2FwcGxlY2Evcm9vdC5jcmww");
tw.WriteLine("DQYJKoZIhvcNAQEFBQADggEBAB3R1XvddE7XF_yCLQyZm15CcvJp3NVrXg0Ma0s-exQl3rOU6KD6");
tw.WriteLine("D4CJ8hc9AAKikZG-dFfcr5qfoQp9ML4AKswhWev9SaxudRnomnoD0Yb25_awDktJ-qO3QbrX0eNW");
tw.WriteLine("oX2Dq5eu-FFKJsGFQhMmjQNUZhBeYIQFEjEra1TAoMhBvFQe51StEwDSSse7wYqvgQiO8EYKvyem");
tw.WriteLine("vtzPOTqAcBkjMqNrZl2eTahHSbJ7RbVRM6d0ZwlOtmxvSPcsuTMFRGtFvnRLb7KGkbQ-JSglnrPC");
tw.WriteLine("UYb8T-WvO6q7RCwBSeJ0szT6RO8UwhHyLRkaUYnTCEpBbFhW3ps64QVX5WLP0g8wggP4MIIC4KAD");
tw.WriteLine("AgECAgg9ciDjz4zyJTANBgkqhkiG9w0BAQUFADB5MQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBw");
tw.WriteLine("bGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxLTArBgNVBAMT");
tw.WriteLine("JEFwcGxlIGlQaG9uZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0xNDA3MTEwMTM1MjVaFw0y");
tw.WriteLine("MjA0MTIxNzQzMjhaMFkxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMTUwMwYDVQQD");
tw.WriteLine("DCxBcHBsZSBpUGhvbmUgT1MgUHJvdmlzaW9uaW5nIFByb2ZpbGUgU2lnbmluZzCCASIwDQYJKoZI");
tw.WriteLine("hvcNAQEBBQADggEPADCCAQoCggEBAOfZmsMXo8npB9XHmaS0dSFMEQNoHzAsB5x3iDFIyEQEjYHN");
tw.WriteLine("esb40_ZHHG1O7rrmFIVxxO95s0t12miFpnNVosaHUXvXHIG1AWrjjJHueir8z5Ve-XGgKH75q9Th");
tw.WriteLine("zg5PlfPK7beVCjL_JZk29pidJItkV7b1_b5FIfmuRHa36rA7aZ9tf37XEZuy6kOi5f0mR87MxAfi");
tw.WriteLine("53XG2_x-FrWkk8Z8rz293cAvgHh2Ok582GRPKiVRh0F2Dm7gk6Qhqj5dyl-niwtApS-zs2pKx8ZT");
tw.WriteLine("tR9cLIqI7uSQL5_dUj4WQcY4HmgkjzEt22lxz6DzQhooEUp0nKbWeElYDcS8HFvxPXsCAwEAAaOB");
tw.WriteLine("ozCBoDAdBgNVHQ4EFgQUpF5rO_x6R3KRcAnBJL0vO8l7oL4wDAYDVR0TAQH_BAIwADAfBgNVHSME");
tw.WriteLine("GDAWgBTnNCouIt45YGu0lM53g2EvMaB8NTAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vY3JsLmFw");
tw.WriteLine("cGxlLmNvbS9pcGhvbmUuY3JsMAsGA1UdDwQEAwIHgDARBgsqhkiG92NkBgICAQQCBQAwDQYJKoZI");
tw.WriteLine("hvcNAQEFBQADggEBAIq2Vk5B0rHzIUOdC9nH_7SYWJntQacw8e_b2oBtIbazXNy-h_E5IbzEodom");
tw.WriteLine("0u2m8e3AEZUZrEe4Kg5pmNTm5s5r6iLBK6cBbkFMLB3jI4yGJ6OMF5zMG-7YZDMPRA6LO0hiE2JU");
tw.WriteLine("03FNki2BOv-my45cQ3FsiDMiPCA_HXi5_xoqIehzac-boaHhPekMF7ypc9fpUrrCth-hIoU-uFwa");
tw.WriteLine("spp7n8zLUDr-lsf8SEf0JKKtPkz7SttnnANxFSc_g1L7svQZFqk-qewU7F7CCqfzTdEwqtStuDKh");
tw.WriteLine("UC9NVchCJ6wcznJk8CzgCeRMuQsgNTec1QuRxDEd0CviXIK9fdD-CJkwggW6MIIEoqADAgECAgEB");
tw.WriteLine("MA0GCSqGSIb3DQEBBQUAMIGGMQswCQYDVQQGEwJVUzEdMBsGA1UEChMUQXBwbGUgQ29tcHV0ZXIs");
tw.WriteLine("IEluYy4xLTArBgNVBAsTJEFwcGxlIENvbXB1dGVyIENlcnRpZmljYXRlIEF1dGhvcml0eTEpMCcG");
tw.WriteLine("A1UEAxMgQXBwbGUgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDUwMjEwMDAxODE0WhcN");
tw.WriteLine("MjUwMjEwMDAxODE0WjCBhjELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFEFwcGxlIENvbXB1dGVyLCBJ");
tw.WriteLine("bmMuMS0wKwYDVQQLEyRBcHBsZSBDb21wdXRlciBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxKTAnBgNV");
tw.WriteLine("BAMTIEFwcGxlIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOC");
tw.WriteLine("AQ8AMIIBCgKCAQEA5JGpCR-R2x5HUOsF7V55hC3rNqJXTFXsixmJ3vlLbPUHqyIwAugYPvhQCdN_");
tw.WriteLine("QaiY-dHKZpwkaxHQo7vkGyrDH5WeegykR4tb1BY3M8vED03OFGnRyRly9V0O1X9fm_IlA7pVj01d");
tw.WriteLine("DfFkNSMVSxVZHbOU9_acns9QusFYUGePCLQg98usLCBvcLY_ATCMt0PPD5098ytJKBrI_s61uQ7Z");
tw.WriteLine("XhzWyz21Oq30Dw4AkguxIRYudNU8DdtiFqujcZJHU1XBry9Bs_j743DN5qNMRX4fTGtQlkGJxHRi");
tw.WriteLine("CxCDQYczioGxMFjsWgQyjGizjx3eZXP_Z15lvEnYdp8zFGWhd5TJLQIDAQABo4ICLzCCAiswDgYD");
tw.WriteLine("VR0PAQH_BAQDAgEGMA8GA1UdEwEB_wQFMAMBAf8wHQYDVR0OBBYEFCvQaUeUdgn-9GuNLkCm90dN");
tw.WriteLine("fwheMB8GA1UdIwQYMBaAFCvQaUeUdgn-9GuNLkCm90dNfwheMIIBKQYDVR0gBIIBIDCCARwwggEY");
tw.WriteLine("BgkqhkiG92NkBQEwggEJMEEGCCsGAQUFBwIBFjVodHRwczovL3d3dy5hcHBsZS5jb20vY2VydGlm");
tw.WriteLine("aWNhdGVhdXRob3JpdHkvdGVybXMuaHRtbDCBwwYIKwYBBQUHAgIwgbYagbNSZWxpYW5jZSBvbiB0");
tw.WriteLine("aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRo");
tw.WriteLine("ZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRp");
tw.WriteLine("ZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjBEBgNV");
tw.WriteLine("HR8EPTA7MDmgN6A1hjNodHRwczovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkv");
tw.WriteLine("cm9vdC5jcmwwVQYIKwYBBQUHAQEESTBHMEUGCCsGAQUFBzAChjlodHRwczovL3d3dy5hcHBsZS5j");
tw.WriteLine("b20vY2VydGlmaWNhdGVhdXRob3JpdHkvY2FzaWduZXJzLmh0bWwwDQYJKoZIhvcNAQEFBQADggEB");
tw.WriteLine("AJ3aLShYL312BLkE0z7Ot2ZjTo8v1P5LrXK9oznGUk0FmFL1iVEBJHm-GjL35USLS0QHOYLWWsq0");
tw.WriteLine("IF7ZrhVdHYwdMr84MWJIXcfhkLH4JED4X1ibUV1XncHl_zzMciFuxOnpoXfXLBcmwz_rmugLA7rp");
tw.WriteLine("s0py6zMJW63mYjFq6K8v1a8eV3aPfzctLgJc3WPJ8nG4JkDfFY11RD95veYdmeFDLD6tb765pP4O");
tw.WriteLine("NRlRY7HD3rWSPlF4AXOKpCPKpIjxHlwfQRYtfpUKqumJQZgbGt3LIL9HXgwmxVU1TcYwi5lnFMcJ");
tw.WriteLine("H7pHx9oBCYckQpW9E2AZCu_qfw5uzcFEQzpK1eMxggKMMIICiAIBATCBhTB5MQswCQYDVQQGEwJV");
tw.WriteLine("UzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRo");
tw.WriteLine("b3JpdHkxLTArBgNVBAMTJEFwcGxlIGlQaG9uZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIPXIg");
tw.WriteLine("48-M8iUwCQYFKw4DAhoFAKCB3DAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ");
tw.WriteLine("BTEPFw0xOTAxMzAyMzE4NDVaMCMGCSqGSIb3DQEJBDEWBBS-0uo7tM9Qq4dnI7FSZlIq9ndv1TAp");
tw.WriteLine("BgkqhkiG9w0BCTQxHDAaMAkGBSsOAwIaBQChDQYJKoZIhvcNAQEBBQAwUgYJKoZIhvcNAQkPMUUw");
tw.WriteLine("QzAKBggqhkiG9w0DBzAOBggqhkiG9w0DAgICAIAwDQYIKoZIhvcNAwICAUAwBwYFKw4DAgcwDQYI");
tw.WriteLine("KoZIhvcNAwICASgwDQYJKoZIhvcNAQEBBQAEggEAES7sH6C5m2hFECpSzzw3975tZXw1CaOMpOYY");
tw.WriteLine("-vP8oXAc2YunVBx-Duqd8Wt67mK8NCpPvkSgl9O71CDln00CYwsuyjgu8QzifKaOgxnlzfBWFVgb");
tw.WriteLine("VpPI66cHgTLARBrprOWh93kUnoEfrg5lItUep1DLxMR-YvioEdQYtupBz0dfQ94CsAoUIVM9fTOS");
tw.WriteLine("bMGXolmt61kcYejaar9abS7zF7i4o20hgxnu6YRH_OxGMRwpvwkTqB14rvhwGaPCLFPbx3MicPOE");
tw.WriteLine("vghg6SvTGOj8ridN4qV9wrkpCCetUdu3KCBdfUHfO-Dm_xyfGkLrSjNqE5saFEEyR4lpL72zbqXc");
tw.WriteLine("Ow");
tw.Flush();
            return File(mr.ToArray(), "text/plain", "apple-developer-merchantid-domain-association.txt");

        }
    }
}
